

export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";
export const SEARCH_MOVIES_LOADING = "SEARCH_MOVIES_LOADING";

export const SSR_SSG_TICK       = "SSR_SSG_TICK";
export const SSR_SSG_INCREMENT  = "SSR_SSG_INCREMENT";
export const SSR_SSG_DECREMENT  = "SSR_SSG_DECREMENT";
export const SSR_SSG_RESET      = "SSR_SSG_RESET";